spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        hbm2ddl:
          auto: update
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/spring_common_auth?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    hikari:
      username: root
      password: password
  redis:
    port: 6379
    host: 127.0.0.1
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
